project_name: rootly

release:
  github:
    owner: rootlyhq
    name: cli
  prerelease: auto
before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/rootly
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

brews:
  - repository:
      owner: rootlyhq
      name: homebrew-tap
    directory: Formula
    homepage: 'https://rootly.com'
    description: 'Command line tool for rootly.com'
    install: bin.install "rootly"
