name: lint

on:
  - push
  - pull_request

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        env:
          GO111MODULE: off
        with:
          go-version: 1.22
        id: go
      - name: Run Golangci Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        env:
          GO111MODULE: off
        with:
          go-version: 1.22
        id: go
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting docker/Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'Dockerfile'
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Check
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: check
